config/routes.rb
Rails.application.routes.draw do
  
  resources :book_requests, only: [:create, :destroy, :index]

  resources :categories

  resources :books

  root             'static_pages#home'

  get 'home'    => 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  devise_for :users, path_names: {sign_up: 'register',  sign_in: 'login', sign_out: 'logout'}
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]
  ActiveAdmin.routes(self)

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  has_attached_file :document, styles: {thumb: ["595x842>", :png]},
                    url:  "/uploads/:class/:attachment/:id_:style.:extension",
                    path: ":rails_root/public:url"

  validates :category_id, presence: true
  validates_attachment :document,
        presence: true,
        size: {in: 0..100.megabytes}
        # content_type: {content_type: "application/pdf"} # gem bug
  do_not_validate_attachment_file_type :document

  scope :categories, -> category_id {where category_id: category_id}

  def self.search_by_title query_title
    if query_title
      where "title LIKE ?", "%#{query_title}%"
    else
      Book.all
    end
  end
end

app/models/book_request.rb
class BookRequest < ActiveRecord::Base
  
  belongs_to :user
  validates :user_id, presence: true
  validates :description, presence:true

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: :User
  belongs_to :followed, class_name: :User

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :active_relationships,  class_name: :Relationship,
           foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: :Relationship,
           foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :book_requests, dependent: :destroy

  enum role: [ :admin, :member ]

  before_validation :normalize_attributes
  validates :role, inclusion: {in: User.roles.keys}
  
  def follow(other_user)
    active_relationships.create followed_id: other_user.id
  end

  def unfollow(other_user)
    active_relationship = active_relationships.find_by followed_id: other_user.id
    active_relationship.destroy
  end

  def following?(other_user)
    following.include? other_user
  end

  private
  def normalize_attributes
    self.role ||= :member
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_admin_user!
    if !current_user
      redirect_to new_user_session_path
    elsif !current_user.try(:admin?)
      flash[:danger] = "You don’t have permission to access Administrator Panel."
      redirect_to root_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/book_requests_controller.rb
class BookRequestsController < InheritedResources::Base
  
  before_action :user_signed_in?, only: [:index, :create, :destroy]
  
  def create
    @book_request = current_user.book_requests.build book_request_params
    if @book_request.save
      flash[:success] = "Book request created!"
      redirect_to book_requests_path
    else
      @book_requests = current_user.book_requests
      render :index
    end
  end
  
  def index
    if user_signed_in?
      @book_requests = current_user.book_requests
      @book_request = current_user.book_requests.build
    else
      redirect_to root_url
    end
  end

  def destroy
    book_request = BookRequest.find(params[:id]).destroy
    if book_request.destroyed?  
      flash[:success] = "Book request deleted!"
    else
      flash[:danger] = "Could not delete!"
    end
    redirect_to book_requests_path
  end

  private

  def book_request_params
    params.require(:book_request).permit :isbn, :description, :state, :user_id
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @books = Book.search_by_title params[:title_query]
    if params.has_key?(:category_query) && params[:category_query].to_s != "all"
      @books = @books.categories params[:category_query]
    end
  end

  def show
    @book = Book.find params[:id]
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    @book.document = params[:book][:document]
    flash[:notice] = 'Upload new book successfully.' if @book.save
    respond_with @book
  end

  private
  def book_params
    params.require(:book).permit :isbn, :title, :edition, :author, :category_id
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find params[:id]
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :user_signed_in?

  def create
    @user = User.find params[:followed_id]
    current_user.follow @user
    respond_to do |format|
      format.html {redirect_to @user}
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow @user
    respond_to do |format|
      format.html {redirect_to @user}
      format.js
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users = User.all
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?
  
  def show
    @user = User.find params[:id]
    @followers = @user.followers
    @following = @user.following
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Book Reviewing System"
    if page_title.blank?
      base_title
    else
      "#{page_title.squish} | #{base_title}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def cover_url(book)
    book.cover || 'missing_book_cover.svg'
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_url(user, options = {size: 80})
    if user.avatar.present?
      user.avatar
    else
      size        = options[:size]
      # default_url = "#{root_url}images/guest.png"
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end
  end
  def current_user?(user)
    user == current_user
  end
end

app/views/book_requests/_book_request.html.erb
<tr>
  <td><%= book_request.isbn %></td>
  <td><%= book_request.description %></td>
  <% if book_request.state == 0 %>
    <td>pending</td>
  </td>
  <% else %>
    <td>solved</td>
  <% end %>
  <% if current_user? book_request.user %>
    <td><%= link_to 'Delete', book_request, method: :delete, 
            class: 'btn btn-default', data: {confirm: "You sure?"} %></td>
  <% end %>
</tr>

app/views/book_requests/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="book_request_form">
        <%= render 'shared/book_request_form' %>
      </section>
    </aside>
  </div>
<h1>Listing Book Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Description</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>
    <%= render @book_requests %>
  </tbody>
</table>

<br>

app/views/books/_advance_search_form.html.erb
<form class="navbar-form navbar-left" role="search" action="/books">
  <div class="input-group">
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">Book Title</span>
      <input type="text" class="form-control" 
             name="title_query" placeholder="Book title..."/><br>
    </div>
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">Book Categories</span>
      <select name="category_query" class="form-control">
        <option value="all">All</option>
        <%= Category.all.each do |category| %>
        <option value=<%=category.id%>><%=category.name %></option>
        <% end %>
      </select>
    </div>
    <button type="submit" class="btn btn-default">
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </button><br>
  </div>
</form>

app/views/books/_book.html.erb
<tr>
  <td><%= book.isbn %></td>
  <td><%= book.title %></td>
  <td><%= book.edition %></td>
  <td><%= book.publish_date %></td>
  <td><%= book.author %></td>
  <td><%= book.number_of_pages %></td>
  <td><%= Category.find(book.category_id).name %></td>
  <td><%= link_to 'Show', book, class: 'btn btn-default' %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for @book, html: {multipart: true} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :isbn, "ISBN" %>
    <%= f.text_field :isbn, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :edition %>
    <%= f.text_field :edition, class: 'form-control', type: 'number', min: 1 %>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name,
        {prompt: ' -- select a category -- '},
        {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.file_field :document, accept: "application/pdf" %>
  </div>

  <div class="btn-toolbar" role="toolbar">
    <%= f.submit "Submit", class: "btn btn-primary pull-right", type: "submit" %>
    <%= f.submit "Reset",  class: "btn btn-default pull-right", type: "reset"  %>
  </div>
<% end %>

app/views/books/_search_form.html.erb
<form class="navbar-form navbar-left" role="search" action="/books">
  <div class="input-group">
    <input type="text" class="form-control" 
           name="title_query" placeholder="Book title...">
      <span class="input-group-btn">
      <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      </button>
    </span>
  </div>
</form>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div>
<h1>Advanced Search</h1>
<%= render "books/advance_search_form" %>
</div>
<div>
<h1>Listing Books</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Isbn</th>
      <th>Title</th>
      <th>Edition</th>
      <th>Publish date</th>
      <th>Author</th>
      <th>Number of pages</th>
      <th>Category</th>
      <th colspan="3">Book operators</th>
    </tr>
  </thead>

  <tbody>
    <%= render @books %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<% provide(:title, 'Uploading book') %>

<div class="panel panel-success pannel-form">
  <div class="panel-heading">
    <h3 class="panel-title">
      <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
      Uploading book...
    </h3>
  </div>
  <div class="panel-body pannel-form-body">
    <%= render 'form' %>
  </div>
</div>

app/views/books/show.html.erb
<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @book.edition %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @book.publish_date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.number_of_pages %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@book.category_id).name %>
</p>

<%= link_to 'Back', books_path, class: 'btn btn-default' %>

app/views/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td><%= category.description %></td>
  <td><%= link_to 'Show', category, class: 'btn btn-default' %></td>
</tr>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize @category.errors.count, "error" %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3">Operations</th>
    </tr>
  </thead>

  <tbody>
    <%= render @categories %>
  </tbody>
</table>

<br>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>
<%= link_to 'Back', categories_path, class: 'btn btn-default' %>

app/views/layouts/_debugger.html.erb
<% if Rails.env.development? %>
  <div class="container">
    <%= debug params %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, class: "alert alert-#{type} alert-dismissible",
                        role: "alert" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <small>
      The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <div>
      <ul>
        <li><%= link_to "Help",    help_path    %></li>
        <li><%= link_to "About",   about_path   %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <span class="helper"></span>
          <%= image_tag 'site_logo.svg', alt: 'Book Reviewing System', 
                                         height: '36', width: '36' %>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to books_path do %>
              Dashboard
              <span class="sr-only">(current)</span>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to "Request", book_requests_path %>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
               role="button" aria-expanded="false">
              Category
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu" name="category">
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, action="/books" %></li>
              <% end %>
            </ul>
          </li>
        </ul>
        <%= render 'books/search_form' %> 
        <ul class="nav navbar-nav navbar-right">
          <%= render 'users/shared/nav' %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= favicon_link_tag 'site_logo.png', type: 'image/png', rel: 'icon' %>
    <%= favicon_link_tag 'site_logo.png', type: 'image/png', rel: 'apple-touch-icon' %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= render 'layouts/shim' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="container">
        <%= render 'layouts/flash' %>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/debugger' %>
  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_book_request_form.html.erb
<% if user_signed_in? %>
  <%= form_for @book_request do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.text_area :description, placeholder: "Book description..." %>
    </div>
    <div class="field">
      <%= f.number_field :isbn %>
    </div>
    <%= f.submit "Make Request", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">

  <%= link_to @user.following.count.to_s + " following",
              user_path(@user, :anchor => "following") %>

  <%= link_to @user.followers.count.to_s + " followers",
              user_path(@user, :anchor => "followers") %>
</div>

app/views/shared/_user_info.html.erb
<% if user_signed_in? %>
  <h1><%= current_user.name %></h1>
  <span><%= link_to "view my profile", current_user %></span>
  <span><%= pluralize(current_user.book_requests.count, "book_request") %></span>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

<p>
  The <a href="http://www.railstutorial.org/">
  <em>Ruby on Rails Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3">Operations</th>
      </tr>
    </thead>

    <tbody>
      <%= render @users %>
    </tbody>
  </table>

  <br>

<% else %>
  <div class="jumbotron">
    <h1>Book Reviewing System</h1>
    <p>Framgia has many technical books that all employees can read. To manage and use them effectively, the management and reviewing system is needed.</p>
  </div>
  <p>This is some text.</p>
  <p>This is another text.</p>
<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user? @user %>
  <div id="follow_form">
  <% if current_user.following? @user %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_show_follow.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Operations</th>
    </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>
<br>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete},
             remote: true  do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= link_to 'Show', user, class: 'btn btn-default' %></td>
</tr>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_nav.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
    <%= link_to '#', class: "dropdown-toggle", 'data-toggle' => "dropdown" do %>
      <span class="helper"></span>
      <%= image_tag avatar_url(current_user, size: 32),
                    alt: current_user.name, class: "circle-image" %>
      <div class="user-nav">
        <%= current_user.name %> <span class="caret"></span>
      </div>
      <ul class="dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path do %>
          Profile
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
          <% end %>
        </li>
        <li>
          <%= link_to '#' do %>
            Settings
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
          <% end %>
        </li>
        <% if current_user.admin? %>
        <li>
          <%= link_to admin_root_path do %>
            Admin
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          <% end %>
        </li>
        <% end %>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            Log out
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
          <% end %>
        </li>
      </ul>
    <% end %>
  </li>
<% else %>
  <li>
    <%= link_to new_user_registration_path do %>
      <span class="glyphicon glyphicon-user"></span> Register
    <% end %>
  </li>
  <li>
    <%= link_to new_user_session_path do %>
      <span class="glyphicon glyphicon-log-in"></span> Login
    <% end %>
  </li>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<%= render 'shared/stats' %>
<%= render 'follow_form' if user_signed_in? %>

<div id="following" >
  <h1>Following users</h1>
  <% @users = @following %>
  <%= render 'show_follow' %>
</div>

<div id="followers">
  <h1>Follower users</h1>
  <%= @users = @followers %>
  <%= render 'show_follow' %>
</div>

<%= link_to 'Back', home_path, class: 'btn btn-default' %>